name: format
on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}-v2
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm install --production=false

      - name: Run Prettier
        run: npx prettier --write ./src/**/*.{ts,tsx}
